#!/usr/bin/env bash
#Prints numbers from 1 to 100 expect the ones that are a multipler of 15, 5, or 3
for i in {1..100}; do
        if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
                echo FizzBuzz
        elif [ $((i % 3)) -eq 0 ]; then
                echo Fizz
        elif [ $((i % 5)) -eq 0 ]; then
                echo Buzz
        else
                echo "$i"
        fi
done
