#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code, sorted by occurrence count

awk '{print $1, $9}' | awk '{count[$1" "$2]++} END {for (key in count) print count[key], key}' | sort -rn
