#!/usr/bin/env bash
#Prints bad luck from China, bad luck from Japan, bad luck from Italy for 4th, 8th and 17th iterations
i=1
while [ "$i" -ne 21 ]
do
        echo $i
        case $i in
                4)
                        echo bad luck from China
                ;;

                9)
                        echo bad luck from Japan
                ;;

                17)
                        echo bad luck from Italy
                ;;
        esac
        _=$((i+=1))
done
