#!/usr/bin/env bash
#Clock program where prints minutes and hours in their cycles
hours=12
minutes=1
temp=0
while [ "$hours" -ne 0 ]
do
        echo Hour: $temp
        while [ "$minutes" -ne 60 ]
        do
                echo $minutes
                _=$((minutes += 1))
        done
        _=$((temp += 1))
        _=$((minutes = 1))
        _=$((hours -= 1))

        if [ "$temp" -eq 12 ]; then
                echo Hour: $temp
        fi
done
