#!/usr/bin/env bash
#Prints the directory in a nice and clean way
for i in *; do
        if [ "$i" == "*" ]; then
                continue
        fi
        if [ "$i" == "*_*" ]; then
                echo "${i#*-}"
        fi
done
