#!/usr/bin/env bash
#Displays information about the school file
if [ -e $school ]; then
        echo school file exists
	
	if [ -f $school ]; then
                echo school is a regular file
        fi

        if [ -s $school ]; then
                echo school file not is empty
        else
                echo school file is empty
        fi
else
        echo school file does not exist
fi
