#!/usr/bin/env bash
#PIDfile
PIDFILE="/var/run/myscript.pid"
echo $$ > "$PIDFILE"
while true
do
echo "To infinity and beyond"
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$PIDFILE"' SIGQUIT
done
